### PR TITLE
Do not hide every value behind asterisks in case of secret create

### LINKED ISSUE #315: fix(secret/create): Amazon AWS region and access key ID fields should be visible
**Describe the bug**

Currently the Amazon secret creation interactive form hides all of the AWS region, access key ID and access key secret characters behind asterisks.

**Steps to reproduce the issue:**

1. `banzai secret create`,
2. Choose `Amazon`,
3. Say `No` to using the default AWS profile,
4. Start typing the AWS region,
5. (observe the input to be hidden behind asterisks),
6. Hit return,
7. Start typing the access key ID,
8. (observe the input to be hidden behind asterisks).

**Expected behavior**

The first two (region and ID) should not be hidden.

### PR DESCRIPTION
**Pull request by colin014**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes #315 
| License         | Apache 2.0

### What's in this PR?
Check `isPassword` of secret type respone to decide the value is an password type or not

### Checklist

- [x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)

### To Do

- [x] Do not merge this PR until https://github.com/banzaicloud/pipeline/pull/3202 is not released

### CODE REVIEW

**Review by pregnor — COMMENTED** [review]
Looks okay considering the API side implementation, what questions I would have had here can be discussed there, the Makefile version is going to require an updated once Pipeline version is available and the files need to be regenerated.

**Review by bonifaido — APPROVED** [review]

File: internal/cli/command/secret/create.go [hunk 1]
```diff
@@ -373,14 +373,23 @@ func surveySecretFields(options *createSecretOptions, secretTypes map[string]pip
...
 		for index, f := range fields {
-			questions[index] = secretFieldQuestion{
-				name: f.Name,
-				input: &survey.Password{
+			sfq := secretFieldQuestion{
+				name:     f.Name,
+				required: f.Required,
+			}
+
+			if f.IsPassword != nil && *f.IsPassword {
```
Comment (pregnor) [inline internal/cli/command/secret/create.go:381]: **Required**: as we discussed in private, this condition is going to need an update one way or another.

**Review by pregnor — CHANGES_REQUESTED** [review]

**Review by pregnor — APPROVED** [review]
